from pyevolve import G1DList, GSimpleGA, Selectors, Scaling, DBAdapters, Initializators, Mutators, Crossovers, Consts
import pyevolve
import math
import cmath
import numpy as np
from numpy import linalg as LA

def lb(k):
	lb=cmath.exp(1j*2*math.pi*k)
	return lb

def lbc(k):
	lbc=cmath.exp(-1j*2*math.pi*k)
	return lbc

def diagonalize(k1, k2, *coeff):
	g0=-3.0622453120228426
	g1=0.20809619698785148
	g2=-0.2331770963650055
	g3=0.06770259188916761
	g4=0.02529974893566056
	g5=-0.01872771772369264
	g6=-0.006704547779572828
	e0=coeff[0]  #0.42060034893339004 #coeff[0] 

	a = np.array(  [[ e0                   , g0                   , g1                   , g1                   , g3                   , g3                   , g4                   , g5                   , g5                   , 0                    , 0                    , 0                    , 0                    , 0                    , g5*lbc(k2)           , g5*lbc(k1)           , 0                    , 0                    , 0                    , g3*lbc(k2)           , g3*lbc(k1)           , g4*lbc(k2)           , g4*lbc(k1)           , g1*lbc(k2)           , g1*lbc(k1)           , 0                    , g3*lbc(k2)           , g3*lbc(k1)           , g5*lbc(k2)           , g5*lbc(k1)           , g0*lbc(k2)           , g0*lbc(k1)           , g1*lbc(k2)           , g1*lbc(k1)           , g6*lbc(k2)           , g6*lbc(k1)           , g2*lbc(k2)           , g2*lbc(k1)           , 0                    , g4*lbc(k2)           , g4*lbc(k1)           , 0                    , g6*lbc(k1)           , g6*lbc(k2)           , 0                    , 0                    , g6*lbc(k1)*lbc(k2)   , g6*lbc(k1)*lbc(k2)   , g4*lbc(k1)*lbc(k2)   , g2*lbc(k1)*lbc(k2)   , 0 , 0 , 0 , 0 , 0 , 0 ] , #1
			[ g0                   , e0                   , g0                   , g0                   , g1                   , g1                   , g2                   , g3                   , g3                   , g4                   , g5                   , g5                   , g6                   , g6                   , 0                    , 0                    , 0                    , 0                    , 0                    , g5*lbc(k2)           , g5*lbc(k1)           , g6*lbc(k2)           , g6*lbc(k1)           , g3*lbc(k2)           , g3*lbc(k1)           , 0                    , g4*lbc(k2)           , g4*lbc(k1)           , g6*lbc(k2)           , g6*lbc(k1)           , g1*lbc(k2)           , g1*lbc(k1)           , g2*lbc(k2)           , g2*lbc(k1)           , g5*lbc(k2)           , g5*lbc(k1)           , g1*lbc(k2)           , g1*lbc(k1)           , 0                    , g3*lbc(k2)           , g3*lbc(k1)           , 0                    , g4*lbc(k1)           , g4*lbc(k2)           , 0                    , 0                    , 0                    , 0                    , 0                    , g4*lbc(k1)*lbc(k2)   , 0 , 0 , 0 , 0 , 0 , 0 ] , #2
			[ g1                   , g0                   , e0                   , g1                   , g0                   , g2                   , g1                   , g1                   , g4                   , g3                   , g3                   , g6                   , g4                   , g5                   , g5                   , 0                    , 0                    , 0                    , 0                    , 0                    , g6*lbc(k1)           , 0                    , g5*lbc(k1)           , g5*lbc(k2)           , g4*lbc(k1)           , 0                    , 0                    , g3*lbc(k1)           , 0                    , g4*lbc(k1)           , g3*lbc(k2)           , g2*lbc(k1)           , g4*lbc(k2)           , g1*lbc(k1)           , 0                    , g3*lbc(k1)           , g3*lbc(k2)           , g0*lbc(k1)           , g5*lbc(k1)           , g5*lbc(k2)           , g1*lbc(k1)           , g6*lbc(k1)           , g2*lbc(k1)           , g6*lbc(k2)           , g4*lbc(k1)           , 0                    , g6*lbc(k1)           , 0                    , 0                    , g6*lbc(k1)*lbc(k2)   , 0 , 0 , 0 , 0 , 0 , 0 ] , #3
			[ g1                   , g0                   , g1                   , e0                   , g2                   , g0                   , g1                   , g4                   , g1                   , g3                   , g6                   , g3                   , g5                   , g4                   , 0                    , g5                   , 0                    , 0                    , 0                    , g6*lbc(k2)           , 0                    , g5*lbc(k2)           , 0                    , g4*lbc(k2)           , g5*lbc(k1)           , 0                    , g3*lbc(k2)           , 0                    , g4*lbc(k2)           , 0                    , g2*lbc(k2)           , g3*lbc(k1)           , g1*lbc(k2)           , g4*lbc(k1)           , g3*lbc(k2)           , 0                    , g0*lbc(k2)           , g3*lbc(k1)           , g5*lbc(k2)           , g1*lbc(k2)           , g5*lbc(k1)           , g6*lbc(k2)           , g6*lbc(k1)           , g2*lbc(k2)           , 0                    , g4*lbc(k2)           , 0                    , g6*lbc(k2)           , 0                    , g6*lbc(k1)*lbc(k2)   , 0 , 0 , 0 , 0 , 0 , 0 ] , #4
			[ g3                   , g1                   , g0                   , g2                   , e0                   , g1                   , g0                   , g0                   , g3                   , g1                   , g1                   , g4                   , g2                   , g3                   , g3                   , 0                    , g5                   , g4                   , g6                   , g5                   , 0                    , g6                   , 0                    , 0                    , 0                    , 0                    , 0                    , g5*lbc(k1)           , 0                    , g6*lbc(k1)           , g5*lbc(k2)           , g4*lbc(k1)           , g6*lbc(k2)           , g3*lbc(k1)           , 0                    , g4*lbc(k1)           , g4*lbc(k2)           , g1*lbc(k1)           , g6*lbc(k1)           , g6*lbc(k2)           , g2*lbc(k1)           , g5*lbc(k1)           , g1*lbc(k1)           , g5*lbc(k2)           , g3*lbc(k1)           , 0                    , g4*lbc(k1)           , 0                    , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #5
			[ g3                   , g1                   , g2                   , g0                   , g1                   , e0                   , g0                   , g3                   , g0                   , g1                   , g4                   , g1                   , g3                   , g2                   , 0                    , g3                   , g4                   , g5                   , g6                   , 0                    , g5                   , 0                    , g6                   , 0                    , 0                    , 0                    , g5*lbc(k2)           , 0                    , g6*lbc(k2)           , 0                    , g4*lbc(k2)           , g5*lbc(k1)           , g3*lbc(k2)           , g6*lbc(k1)           , g4*lbc(k2)           , 0                    , g1*lbc(k2)           , g4*lbc(k1)           , g6*lbc(k2)           , g2*lbc(k2)           , g6*lbc(k1)           , g5*lbc(k2)           , g5*lbc(k1)           , g1*lbc(k2)           , 0                    , g3*lbc(k2)           , 0                    , g4*lbc(k2)           , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #6
			[ g4                   , g2                   , g1                   , g1                   , g0                   , g0                   , e0                   , g1                   , g1                   , g0                   , g2                   , g2                   , g1                   , g1                   , g4                   , g4                   , g3                   , g3                   , g4                   , g6                   , g6                   , g5                   , g5                   , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , g6*lbc(k2)           , g6*lbc(k1)           , g5*lbc(k2)           , g5*lbc(k1)           , 0                    , 0                    , g3*lbc(k2)           , g3*lbc(k1)           , 0                    , g4*lbc(k2)           , g4*lbc(k1)           , 0                    , g3*lbc(k1)           , g3*lbc(k2)           , g5*lbc(k1)           , g5*lbc(k2)           , g6*lbc(k1)           , g6*lbc(k2)           , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #7
			[ g5                   , g3                   , g1                   , g4                   , g0                   , g3                   , g1                   , e0                   , g5                   , g2                   , g0                   , g6                   , g1                   , g4                   , g1                   , 0                    , g6                   , g3                   , g5                   , g3                   , 0                    , g4                   , 0                    , g5                   , 0                    , 0                    , 0                    , g6*lbc(k1)           , 0                    , g5*lbc(k1)           , 0                    , g6*lbc(k1)           , 0                    , g4*lbc(k1)           , 0                    , g3*lbc(k1)           , 0                    , g2*lbc(k1)           , g4*lbc(k1)           , 0                    , g1*lbc(k1)           , g3*lbc(k1)           , g0*lbc(k1)           , 0                    , g1*lbc(k1)           , g5*lbc(k1)           , g2*lbc(k1)           , g6*lbc(k1)           , g4*lbc(k1)           , g6*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #8
			[ g5                   , g3                   , g4                   , g1                   , g3                   , g0                   , g1                   , g5                   , e0                   , g2                   , g6                   , g0                   , g4                   , g1                   , 0                    , g1                   , g3                   , g6                   , g5                   , 0                    , g3                   , 0                    , g4                   , 0                    , g5                   , 0                    , g6*lbc(k2)           , 0                    , g5*lbc(k2)           , 0                    , g6*lbc(k2)           , 0                    , g4*lbc(k2)           , 0                    , g3*lbc(k2)           , 0                    , g2*lbc(k2)           , 0                    , g4*lbc(k2)           , g1*lbc(k2)           , 0                    , g3*lbc(k2)           , 0                    , g0*lbc(k2)           , g5*lbc(k2)           , g1*lbc(k2)           , g6*lbc(k2)           , g2*lbc(k2)           , g4*lbc(k2)           , g6*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #9
			[ 0                    , g4                   , g3                   , g3                   , g1                   , g1                   , g0                   , g2                   , g2                   , e0                   , g1                   , g1                   , g0                   , g0                   , g3                   , g3                   , g1                   , g1                   , g2                   , g4                   , g4                   , g3                   , g3                   , 0                    , 0                    , g4                   , g5                   , g5                   , g6                   , g6                   , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , g5*lbc(k2)           , g5*lbc(k1)           , 0                    , g6*lbc(k2)           , g6*lbc(k1)           , 0                    , g4*lbc(k1)           , g4*lbc(k2)           , g6*lbc(k1)           , g6*lbc(k2)           , g5*lbc(k1)           , g5*lbc(k2)           , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #10
			[ 0                    , g5                   , g3                   , g6                   , g1                   , g4                   , g2                   , g0                   , g6                   , g1                   , e0                   , g5                   , g0                   , g3                   , g0                   , 0                    , g4                   , g1                   , g3                   , g1                   , 0                    , g2                   , 0                    , g3                   , 0                    , g5                   , g4                   , 0                    , g6                   , 0                    , g5                   , 0                    , g6                   , 0                    , 0                    , g5*lbc(k1)           , 0                    , g4*lbc(k1)           , g6*lbc(k1)           , 0                    , g3*lbc(k1)           , g4*lbc(k1)           , g1*lbc(k1)           , 0                    , g2*lbc(k1)           , g6*lbc(k1)           , g1*lbc(k1)           , g5*lbc(k1)           , g3*lbc(k1)           , g4*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #11
			[ 0                    , g5                   , g6                   , g3                   , g4                   , g1                   , g2                   , g6                   , g0                   , g1                   , g5                   , e0                   , g3                   , g0                   , 0                    , g0                   , g1                   , g4                   , g3                   , 0                    , g1                   , 0                    , g2                   , 0                    , g3                   , g5                   , 0                    , g4                   , 0                    , g6                   , 0                    , g5                   , 0                    , g6                   , g5*lbc(k2)           , 0                    , g4*lbc(k2)           , 0                    , g6*lbc(k2)           , g3*lbc(k2)           , 0                    , g4*lbc(k2)           , 0                    , g1*lbc(k2)           , g6*lbc(k2)           , g2*lbc(k2)           , g5*lbc(k2)           , g1*lbc(k2)           , g3*lbc(k2)           , g4*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #12
			[ 0                    , g6                   , g4                   , g5                   , g2                   , g3                   , g1                   , g1                   , g4                   , g0                   , g0                   , g3                   , e0                   , g1                   , g1                   , g5                   , g2                   , g0                   , g1                   , g2                   , g6                   , g1                   , g4                   , g4                   , 0                    , g3                   , g3                   , g6                   , g4                   , g5                   , g6                   , 0                    , g5                   , 0                    , 0                    , 0                    , 0                    , g6*lbc(k1)           , 0                    , 0                    , g5*lbc(k1)           , 0                    , g3*lbc(k1)           , 0                    , g4*lbc(k1)           , 0                    , g3*lbc(k1)           , 0                    , g5*lbc(k1)           , g6*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #13
			[ 0                    , g6                   , g5                   , g4                   , g3                   , g2                   , g1                   , g4                   , g1                   , g0                   , g3                   , g0                   , g1                   , e0                   , g5                   , g1                   , g0                   , g2                   , g1                   , g6                   , g2                   , g4                   , g1                   , 0                    , g4                   , g3                   , g6                   , g3                   , g5                   , g4                   , 0                    , g6                   , 0                    , g5                   , 0                    , 0                    , g6*lbc(k2)           , 0                    , 0                    , g5*lbc(k2)           , 0                    , 0                    , 0                    , g3*lbc(k2)           , 0                    , g4*lbc(k2)           , 0                    , g3*lbc(k2)           , g5*lbc(k2)           , g6*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #14
			[ g5*lb(k2)            , 0                    , g5                   , 0                    , g3                   , 0                    , g4                   , g1                   , 0                    , g3                   , g0                   , 0                    , g1                   , g5                   , e0                   , g5*lbc(k1)*lb(k2)    , g6                   , g2                   , g4                   , g0                   , g6*lbc(k1)*lb(k2)    , g1                   , 0                    , g1                   , g4*lbc(k1)*lb(k2)    , g6                   , g3                   , 0                    , g5                   , 0                    , g3                   , g6*lbc(k1)*lb(k2)    , g4                   , 0                    , 0                    , g6*lbc(k1)           , 0                    , g6*lbc(k1)           , g5*lbc(k1)           , 0                    , g4*lbc(k1)           , g3*lbc(k1)           , g2*lbc(k1)           , 0                    , g1*lbc(k1)           , g4*lbc(k1)           , g0*lbc(k1)           , g3*lbc(k1)           , g1*lbc(k1)           , g2*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #15
			[ g5*lb(k1)            , 0                    , 0                    , g5                   , 0                    , g3                   , g4                   , 0                    , g1                   , g3                   , 0                    , g0                   , g5                   , g1                   , g5*lb(k1)*lbc(k2)    , e0                   , g2                   , g6                   , g4                   , g6*lb(k1)*lbc(k2)    , g0                   , 0                    , g1                   , g4*lb(k1)*lbc(k2)    , g1                   , g6                   , 0                    , g3                   , 0                    , g5                   , g6*lb(k1)*lbc(k2)    , g3                   , 0                    , g4                   , g6*lbc(k2)           , 0                    , g6*lbc(k2)           , 0                    , g5*lbc(k2)           , g4*lbc(k2)           , 0                    , g3*lbc(k2)           , 0                    , g2*lbc(k2)           , g4*lbc(k2)           , g1*lbc(k2)           , g3*lbc(k2)           , g0*lbc(k2)           , g1*lbc(k2)           , g2*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #16
			[ 0                    , 0                    , 0                    , 0                    , g5                   , g4                   , g3                   , g6                   , g3                   , g1                   , g4                   , g1                   , g2                   , g0                   , g6                   , g2                   , e0                   , g1                   , g0                   , g5                   , g1                   , g3                   , g0                   , 0                    , g3                   , g1                   , g4                   , g1                   , g3                   , g2                   , 0                    , g4                   , 0                    , g3                   , g5                   , g4                   , 0                    , g5                   , g6                   , 0                    , g6                   , 0                    , 0                    , g5*lbc(k2)           , 0                    , g6*lbc(k2)           , 0                    , g4*lbc(k2)           , g6*lbc(k2)           , g5*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #17
			[ 0                    , 0                    , 0                    , 0                    , g4                   , g5                   , g3                   , g3                   , g6                   , g1                   , g1                   , g4                   , g0                   , g2                   , g2                   , g6                   , g1                   , e0                   , g0                   , g1                   , g5                   , g0                   , g3                   , g3                   , 0                    , g1                   , g1                   , g4                   , g2                   , g3                   , g4                   , 0                    , g3                   , 0                    , g4                   , g5                   , g5                   , 0                    , g6                   , g6                   , 0                    , 0                    , g5*lbc(k1)           , 0                    , g6*lbc(k1)           , 0                    , g4*lbc(k1)           , 0                    , g6*lbc(k1)           , g5*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #18
			[ 0                    , 0                    , 0                    , 0                    , g6                   , g6                   , g4                   , g5                   , g5                   , g2                   , g3                   , g3                   , g1                   , g1                   , g4                   , g4                   , g0                   , g0                   , e0                   , g3                   , g3                   , g1                   , g1                   , g5                   , g5                   , g0                   , g2                   , g2                   , g1                   , g1                   , g6                   , g6                   , g4                   , g4                   , g3                   , g3                   , g6                   , g6                   , g4                   , g5                   , g5                   , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #19
			[ g3*lb(k2)            , g5*lb(k2)            , 0                    , g6*lb(k2)            , g5                   , 0                    , g6                   , g3                   , 0                    , g4                   , g1                   , 0                    , g2                   , g6                   , g0                   , g6*lbc(k1)*lb(k2)    , g5                   , g1                   , g3                   , e0                   , g5*lbc(k1)*lb(k2)    , g0                   , 0                    , g0                   , g3*lbc(k1)*lb(k2)    , g4                   , g1                   , 0                    , g3                   , 0                    , g1                   , g4*lbc(k1)*lb(k2)    , g2                   , 0                    , g5                   , 0                    , g4                   , 0                    , 0                    , g6                   , 0                    , g5*lbc(k1)           , g4*lbc(k1)           , 0                    , g3*lbc(k1)           , g6*lbc(k1)           , g1*lbc(k1)           , g4*lbc(k1)           , g2*lbc(k1)           , g1*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #20
			[ g3*lb(k1)            , g5*lb(k1)            , g6*lb(k1)            , 0                    , 0                    , g5                   , g6                   , 0                    , g3                   , g4                   , 0                    , g1                   , g6                   , g2                   , g6*lb(k1)*lbc(k2)    , g0                   , g1                   , g5                   , g3                   , g5*lb(k1)*lbc(k2)    , e0                   , 0                    , g0                   , g3*lb(k1)*lbc(k2)    , g0                   , g4                   , 0                    , g1                   , 0                    , g3                   , g4*lb(k1)*lbc(k2)    , g1                   , 0                    , g2                   , 0                    , g5                   , 0                    , g4                   , 0                    , 0                    , g6                   , g5*lbc(k2)           , 0                    , g4*lbc(k2)           , g6*lbc(k2)           , g3*lbc(k2)           , g4*lbc(k2)           , g1*lbc(k2)           , g2*lbc(k2)           , g1*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #21
			[ g4*lb(k2)            , g6*lb(k2)            , 0                    , g5*lb(k2)            , g6                   , 0                    , g5                   , g4                   , 0                    , g3                   , g2                   , 0                    , g1                   , g4                   , g1                   , 0                    , g3                   , g0                   , g1                   , g0                   , 0                    , e0                   , g5                   , g1                   , g5*lbc(k1)*lb(k2)    , g2                   , g0                   , g6                   , g1                   , g4                   , g2                   , g6*lbc(k1)*lb(k2)    , g1                   , 0                    , g3                   , g6                   , g3                   , 0                    , g5                   , g4                   , 0                    , 0                    , g6*lbc(k1)           , 0                    , g5*lbc(k1)           , 0                    , g3*lbc(k1)           , 0                    , g4*lbc(k1)           , g3*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #22
			[ g4*lb(k1)            , g6*lb(k1)            , g5*lb(k1)            , 0                    , 0                    , g6                   , g5                   , 0                    , g4                   , g3                   , 0                    , g2                   , g4                   , g1                   , 0                    , g1                   , g0                   , g3                   , g1                   , 0                    , g0                   , g5                   , e0                   , g5*lb(k1)*lbc(k2)    , g1                   , g2                   , g6                   , g0                   , g4                   , g1                   , g6*lb(k1)*lbc(k2)    , g2                   , 0                    , g1                   , g6                   , g3                   , 0                    , g3                   , g5                   , 0                    , g4                   , 0                    , 0                    , g6*lbc(k2)           , 0                    , g5*lbc(k2)           , 0                    , g3*lbc(k2)           , g4*lbc(k2)           , g3*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #23
			[ g1*lb(k2)            , g3*lb(k2)            , g5*lb(k2)            , g4*lb(k2)            , 0                    , 0                    , 0                    , g5                   , 0                    , 0                    , g3                   , 0                    , g4                   , 0                    , g1                   , g4*lbc(k1)*lb(k2)    , 0                    , g3                   , g5                   , g0                   , g3*lbc(k1)*lb(k2)    , g1                   , g5*lbc(k1)*lb(k2)    , e0                   , g1*lbc(k1)*lb(k2)    , g6                   , g2                   , g6*lbc(k1)*lb(k2)    , g4                   , 0                    , g0                   , g2*lbc(k1)*lb(k2)    , g1                   , g4*lbc(k1)*lb(k2)    , g6                   , 0                    , g3                   , g6*lbc(k1)*lb(k2)    , 0                    , g5                   , 0                    , g6*lbc(k1)           , g6*lbc(k1)           , 0                    , g4*lbc(k1)           , g5*lbc(k1)           , g2*lbc(k1)           , g3*lbc(k1)           , g1*lbc(k1)           , g0*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #24
			[ g1*lb(k1)            , g3*lb(k1)            , g4*lb(k1)            , g5*lb(k1)            , 0                    , 0                    , 0                    , 0                    , g5                   , 0                    , 0                    , g3                   , 0                    , g4                   , g4*lb(k1)*lbc(k2)    , g1                   , g3                   , 0                    , g5                   , g3*lb(k1)*lbc(k2)    , g0                   , g5*lb(k1)*lbc(k2)    , g1                   , g1*lb(k1)*lbc(k2)    , e0                   , g6                   , g6*lb(k1)*lbc(k2)    , g2                   , 0                    , g4                   , g2*lb(k1)*lbc(k2)    , g0                   , g4*lb(k1)*lbc(k2)    , g1                   , 0                    , g6                   , g6*lb(k1)*lbc(k2)    , g3                   , 0                    , 0                    , g5                   , g6*lbc(k2)           , 0                    , g6*lbc(k2)           , g5*lbc(k2)           , g4*lbc(k2)           , g3*lbc(k2)           , g2*lbc(k2)           , g1*lbc(k2)           , g0*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #25
			[ 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , g4                   , g5                   , g5                   , g3                   , g3                   , g6                   , g6                   , g1                   , g1                   , g0                   , g4                   , g4                   , g2                   , g2                   , g6                   , g6                   , e0                   , g1                   , g1                   , g0                   , g0                   , g5                   , g5                   , g3                   , g3                   , g1                   , g1                   , g4                   , g4                   , g2                   , g3                   , g3                   , g4                   , g5                   , g5                   , g6                   , g6                   , 0                    , 0                    , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #26
			[ g3*lb(k2)            , g4*lb(k2)            , 0                    , g3*lb(k2)            , 0                    , g5*lb(k2)            , 0                    , 0                    , g6*lb(k2)            , g5                   , g4                   , 0                    , g3                   , g6                   , g3                   , 0                    , g4                   , g1                   , g2                   , g1                   , 0                    , g0                   , g6                   , g2                   , g6*lbc(k1)*lb(k2)    , g1                   , e0                   , g5                   , g0                   , g3                   , g1                   , g5*lbc(k1)*lb(k2)    , g0                   , 0                    , g1                   , g4                   , g1                   , 0                    , g3                   , g2                   , 0                    , g5                   , 0                    , g4                   , 0                    , g6                   , g5*lbc(k1)           , 0                    , g6*lbc(k1)           , g4*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #27
			[ g3*lb(k1)            , g4*lb(k1)            , g3*lb(k1)            , 0                    , g5*lb(k1)            , 0                    , 0                    , g6*lb(k1)            , 0                    , g5                   , 0                    , g4                   , g6                   , g3                   , 0                    , g3                   , g1                   , g4                   , g2                   , 0                    , g1                   , g6                   , g0                   , g6*lb(k1)*lbc(k2)    , g2                   , g1                   , g5                   , e0                   , g3                   , g0                   , g5*lb(k1)*lbc(k2)    , g1                   , 0                    , g0                   , g4                   , g1                   , 0                    , g1                   , g3                   , 0                    , g2                   , g5                   , g4                   , 0                    , g6                   , 0                    , 0                    , g5*lbc(k2)           , g6*lbc(k2)           , g4*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #28
			[ g5*lb(k2)            , g6*lb(k2)            , 0                    , g4*lb(k2)            , 0                    , g6*lb(k2)            , 0                    , 0                    , g5*lb(k2)            , g6                   , g6                   , 0                    , g4                   , g5                   , g5                   , 0                    , g3                   , g2                   , g1                   , g3                   , 0                    , g1                   , g4                   , g4                   , 0                    , g0                   , g0                   , g3                   , e0                   , g1                   , g3                   , 0                    , g1                   , g5                   , g0                   , g2                   , g2                   , g6                   , g1                   , g1                   , g4                   , g3                   , g6                   , g3                   , g5                   , g4                   , 0                    , 0                    , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #29
			[ g5*lb(k1)            , g6*lb(k1)            , g4*lb(k1)            , 0                    , g6*lb(k1)            , 0                    , 0                    , g5*lb(k1)            , 0                    , g6                   , 0                    , g6                   , g5                   , g4                   , 0                    , g5                   , g2                   , g3                   , g1                   , 0                    , g3                   , g4                   , g1                   , 0                    , g4                   , g0                   , g3                   , g0                   , g1                   , e0                   , 0                    , g3                   , g5                   , g1                   , g2                   , g0                   , g6                   , g2                   , g1                   , g4                   , g1                   , g3                   , g3                   , g6                   , g4                   , g5                   , 0                    , 0                    , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #30
			[ g0*lb(k2)            , g1*lb(k2)            , g3*lb(k2)            , g2*lb(k2)            , g5*lb(k2)            , g4*lb(k2)            , g6*lb(k2)            , 0                    , g6*lb(k2)            , 0                    , g5                   , 0                    , g6                   , 0                    , g3                   , g6*lbc(k1)*lb(k2)    , 0                    , g4                   , g6                   , g1                   , g4*lbc(k1)*lb(k2)    , g2                   , g6*lbc(k1)*lb(k2)    , g0                   , g2*lbc(k1)*lb(k2)    , g5                   , g1                   , g5*lbc(k1)*lb(k2)    , g3                   , 0                    , e0                   , g1*lbc(k1)*lb(k2)    , g0                   , g3*lbc(k1)*lb(k2)    , g4                   , 0                    , g1                   , g4*lbc(k1)*lb(k2)    , 0                    , g3                   , 0                    , 0                    , 0                    , g5                   , 0                    , 0                    , g4*lbc(k1)           , g5*lbc(k1)           , g3*lbc(k1)           , g1*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #31
			[ g0*lb(k1)            , g1*lb(k1)            , g2*lb(k1)            , g3*lb(k1)            , g4*lb(k1)            , g5*lb(k1)            , g6*lb(k1)            , g6*lb(k1)            , 0                    , 0                    , 0                    , g5                   , 0                    , g6                   , g6*lb(k1)*lbc(k2)    , g3                   , g4                   , 0                    , g6                   , g4*lb(k1)*lbc(k2)    , g1                   , g6*lb(k1)*lbc(k2)    , g2                   , g2*lb(k1)*lbc(k2)    , g0                   , g5                   , g5*lb(k1)*lbc(k2)    , g1                   , 0                    , g3                   , g1*lb(k1)*lbc(k2)    , e0                   , g3*lb(k1)*lbc(k2)    , g0                   , 0                    , g4                   , g4*lb(k1)*lbc(k2)    , g1                   , 0                    , 0                    , g3                   , 0                    , g5                   , 0                    , 0                    , 0                    , g5*lbc(k2)           , g4*lbc(k2)           , g3*lbc(k2)           , g1*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #32
			[ g1*lb(k2)            , g2*lb(k2)            , g4*lb(k2)            , g1*lb(k2)            , g6*lb(k2)            , g3*lb(k2)            , g5*lb(k2)            , 0                    , g4*lb(k2)            , 0                    , g6                   , 0                    , g5                   , 0                    , g4                   , 0                    , 0                    , g3                   , g4                   , g2                   , 0                    , g1                   , 0                    , g1                   , g4*lbc(k1)*lb(k2)    , g3                   , g0                   , 0                    , g1                   , g5                   , g0                   , g3*lbc(k1)*lb(k2)    , e0                   , g5*lbc(k1)*lb(k2)    , g2                   , g6                   , g0                   , g6*lbc(k1)*lb(k2)    , g4                   , g1                   , 0                    , g6                   , 0                    , g3                   , 0                    , g5                   , g6*lbc(k1)           , 0                    , g5*lbc(k1)           , g3*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #33
			[ g1*lb(k1)            , g2*lb(k1)            , g1*lb(k1)            , g4*lb(k1)            , g3*lb(k1)            , g6*lb(k1)            , g5*lb(k1)            , g4*lb(k1)            , 0                    , 0                    , 0                    , g6                   , 0                    , g5                   , 0                    , g4                   , g3                   , 0                    , g4                   , 0                    , g2                   , 0                    , g1                   , g4*lb(k1)*lbc(k2)    , g1                   , g3                   , 0                    , g0                   , g5                   , g1                   , g3*lb(k1)*lbc(k2)    , g0                   , g5*lb(k1)*lbc(k2)    , e0                   , g6                   , g2                   , g6*lb(k1)*lbc(k2)    , g0                   , g4                   , 0                    , g1                   , g6                   , g3                   , 0                    , g5                   , 0                    , 0                    , g6*lbc(k2)           , g5*lbc(k2)           , g3*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #34
			[ g6*lb(k2)            , g5*lb(k2)            , 0                    , g3*lb(k2)            , 0                    , g4*lb(k2)            , 0                    , 0                    , g3*lb(k2)            , 0                    , 0                    , g5*lb(k2)            , 0                    , 0                    , 0                    , g6*lb(k2)            , g5                   , g4                   , g3                   , g5                   , 0                    , g3                   , g6                   , g6                   , 0                    , g1                   , g1                   , g4                   , g0                   , g2                   , g4                   , 0                    , g2                   , g6                   , e0                   , g1                   , g1                   , g5                   , g0                   , g0                   , g3                   , g1                   , g4                   , g1                   , g3                   , g2                   , g5                   , g4                   , g6                   , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #35
			[ g6*lb(k1)            , g5*lb(k1)            , g3*lb(k1)            , 0                    , g4*lb(k1)            , 0                    , 0                    , g3*lb(k1)            , 0                    , 0                    , g5*lb(k1)            , 0                    , 0                    , 0                    , g6*lb(k1)            , 0                    , g4                   , g5                   , g3                   , 0                    , g5                   , g6                   , g3                   , 0                    , g6                   , g1                   , g4                   , g1                   , g2                   , g0                   , 0                    , g4                   , g6                   , g2                   , g1                   , e0                   , g5                   , g1                   , g0                   , g3                   , g0                   , g1                   , g1                   , g4                   , g2                   , g3                   , g4                   , g5                   , g6                   , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #36
			[ g2*lb(k2)            , g1*lb(k2)            , g3*lb(k2)            , g0*lb(k2)            , g4*lb(k2)            , g1*lb(k2)            , g3*lb(k2)            , 0                    , g2*lb(k2)            , g5*lb(k2)            , 0                    , g4*lb(k2)            , 0                    , g6*lb(k2)            , 0                    , g6*lb(k2)            , 0                    , g5                   , g6                   , g4                   , 0                    , g3                   , 0                    , g3                   , g6*lbc(k1)*lb(k2)    , g4                   , g1                   , 0                    , g2                   , g6                   , g1                   , g4*lbc(k1)*lb(k2)    , g0                   , g6*lbc(k1)*lb(k2)    , g1                   , g5                   , e0                   , g5*lbc(k1)*lb(k2)    , g3                   , g0                   , 0                    , g4                   , 0                    , g1                   , 0                    , g3                   , 0                    , g5                   , 0                    , g5*lbc(k1)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #37
			[ g2*lb(k1)            , g1*lb(k1)            , g0*lb(k1)            , g3*lb(k1)            , g1*lb(k1)            , g4*lb(k1)            , g3*lb(k1)            , g2*lb(k1)            , 0                    , g5*lb(k1)            , g4*lb(k1)            , 0                    , g6*lb(k1)            , 0                    , g6*lb(k1)            , 0                    , g5                   , 0                    , g6                   , 0                    , g4                   , 0                    , g3                   , g6*lb(k1)*lbc(k2)    , g3                   , g4                   , 0                    , g1                   , g6                   , g2                   , g4*lb(k1)*lbc(k2)    , g1                   , g6*lb(k1)*lbc(k2)    , g0                   , g5                   , g1                   , g5*lb(k1)*lbc(k2)    , e0                   , g3                   , 0                    , g0                   , g4                   , g1                   , 0                    , g3                   , 0                    , g5                   , 0                    , 0                    , g5*lbc(k2)           , 0 , 0 , 0 , 0 , 0 , 0 ] , #38
			[ 0                    , 0                    , g5*lb(k1)            , g5*lb(k2)            , g6*lb(k1)            , g6*lb(k2)            , 0                    , g4*lb(k1)            , g4*lb(k2)            , 0                    , g6*lb(k1)            , g6*lb(k2)            , 0                    , 0                    , g5*lb(k1)            , g5*lb(k2)            , g6                   , g6                   , g4                   , 0                    , 0                    , g5                   , g5                   , 0                    , 0                    , g2                   , g3                   , g3                   , g1                   , g1                   , 0                    , 0                    , g4                   , g4                   , g0                   , g0                   , g3                   , g3                   , e0                   , g1                   , g1                   , g0                   , g2                   , g2                   , g1                   , g1                   , g3                   , g3                   , g4                   , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #39
			[ g4*lb(k2)            , g3*lb(k2)            , g5*lb(k2)            , g1*lb(k2)            , g6*lb(k2)            , g2*lb(k2)            , g4*lb(k2)            , 0                    , g1*lb(k2)            , g6*lb(k2)            , 0                    , g3*lb(k2)            , 0                    , g5*lb(k2)            , 0                    , g4*lb(k2)            , 0                    , g6                   , g5                   , g6                   , 0                    , g4                   , 0                    , g5                   , 0                    , g3                   , g2                   , 0                    , g1                   , g4                   , g3                   , 0                    , g1                   , 0                    , g0                   , g3                   , g0                   , 0                    , g1                   , e0                   , g5                   , g2                   , g6                   , g0                   , g4                   , g1                   , g6                   , g3                   , g5                   , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #40
			[ g4*lb(k1)            , g3*lb(k1)            , g1*lb(k1)            , g5*lb(k1)            , g2*lb(k1)            , g6*lb(k1)            , g4*lb(k1)            , g1*lb(k1)            , 0                    , g6*lb(k1)            , g3*lb(k1)            , 0                    , g5*lb(k1)            , 0                    , g4*lb(k1)            , 0                    , g6                   , 0                    , g5                   , 0                    , g6                   , 0                    , g4                   , 0                    , g5                   , g3                   , 0                    , g2                   , g4                   , g1                   , 0                    , g3                   , 0                    , g1                   , g3                   , g0                   , 0                    , g0                   , g1                   , g5                   , e0                   , g2                   , g0                   , g6                   , g1                   , g4                   , g3                   , g6                   , g5                   , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #41
			[ 0                    , 0                    , g6*lb(k1)            , g6*lb(k2)            , g5*lb(k1)            , g5*lb(k2)            , 0                    , g3*lb(k1)            , g3*lb(k2)            , 0                    , g4*lb(k1)            , g4*lb(k2)            , 0                    , 0                    , g3*lb(k1)            , g3*lb(k2)            , 0                    , 0                    , 0                    , g5*lb(k1)            , g5*lb(k2)            , 0                    , 0                    , g6*lb(k1)            , g6*lb(k2)            , g4                   , g5                   , g5                   , g3                   , g3                   , 0                    , 0                    , g6                   , g6                   , g1                   , g1                   , g4                   , g4                   , g0                   , g2                   , g2                   , e0                   , g1                   , g1                   , g0                   , g0                   , g1                   , g1                   , g2                   , g4                   , 0 , 0 , 0 , 0 , 0 , 0 ] , #42
			[ g6*lb(k1)            , g4*lb(k1)            , g2*lb(k1)            , g6*lb(k1)            , g1*lb(k1)            , g5*lb(k1)            , g3*lb(k1)            , g0*lb(k1)            , 0                    , g4*lb(k1)            , g1*lb(k1)            , 0                    , g3*lb(k1)            , 0                    , g2*lb(k1)            , 0                    , 0                    , g5*lb(k1)            , 0                    , g4*lb(k1)            , 0                    , g6*lb(k1)            , 0                    , g6*lb(k1)            , 0                    , g5                   , 0                    , g4                   , g6                   , g3                   , 0                    , g5                   , 0                    , g3                   , g4                   , g1                   , 0                    , g1                   , g2                   , g6                   , g0                   , g1                   , e0                   , g5                   , g0                   , g3                   , g1                   , g4                   , g3                   , g5                   , 0 , 0 , 0 , 0 , 0 , 0 ] , #43
			[ g6*lb(k2)            , g4*lb(k2)            , g6*lb(k2)            , g2*lb(k2)            , g5*lb(k2)            , g1*lb(k2)            , g3*lb(k2)            , 0                    , g0*lb(k2)            , g4*lb(k2)            , 0                    , g1*lb(k2)            , 0                    , g3*lb(k2)            , 0                    , g2*lb(k2)            , g5*lb(k2)            , 0                    , 0                    , 0                    , g4*lb(k2)            , 0                    , g6*lb(k2)            , 0                    , g6*lb(k2)            , g5                   , g4                   , 0                    , g3                   , g6                   , g5                   , 0                    , g3                   , 0                    , g1                   , g4                   , g1                   , 0                    , g2                   , g0                   , g6                   , g1                   , g5                   , e0                   , g3                   , g0                   , g4                   , g1                   , g3                   , g5                   , 0 , 0 , 0 , 0 , 0 , 0 ] , #44
			[ 0                    , 0                    , g4*lb(k1)            , 0                    , g3*lb(k1)            , 0                    , g5*lb(k1)            , g1*lb(k1)            , g5*lb(k2)            , g6*lb(k1)            , g2*lb(k1)            , g6*lb(k2)            , g4*lb(k1)            , 0                    , g1*lb(k1)            , g4*lb(k2)            , 0                    , g6*lb(k1)            , 0                    , g3*lb(k1)            , g6*lb(k2)            , g5*lb(k1)            , 0                    , g4*lb(k1)            , g5*lb(k2)            , g6                   , 0                    , g6                   , g5                   , g4                   , 0                    , 0                    , 0                    , g5                   , g3                   , g2                   , 0                    , g3                   , g1                   , g4                   , g1                   , g0                   , g0                   , g3                   , e0                   , g1                   , g0                   , g2                   , g1                   , g3                   , 0 , 0 , 0 , 0 , 0 , 0 ] , #45
			[ 0                    , 0                    , 0                    , g4*lb(k2)            , 0                    , g3*lb(k2)            , g5*lb(k2)            , g5*lb(k1)            , g1*lb(k2)            , g6*lb(k2)            , g6*lb(k1)            , g2*lb(k2)            , 0                    , g4*lb(k2)            , g4*lb(k1)            , g1*lb(k2)            , g6*lb(k2)            , 0                    , 0                    , g6*lb(k1)            , g3*lb(k2)            , 0                    , g5*lb(k2)            , g5*lb(k1)            , g4*lb(k2)            , g6                   , g6                   , 0                    , g4                   , g5                   , 0                    , 0                    , g5                   , 0                    , g2                   , g3                   , g3                   , 0                    , g1                   , g1                   , g4                   , g0                   , g3                   , g0                   , g1                   , e0                   , g2                   , g0                   , g1                   , g3                   , 0 , 0 , 0 , 0 , 0 , 0 ] , #46
			[ g6*lb(k1)*lb(k2)     , 0                    , g6*lb(k1)            , 0                    , g4*lb(k1)            , 0                    , g6*lb(k1)            , g2*lb(k1)            , g6*lb(k2)            , g5*lb(k1)            , g1*lb(k1)            , g5*lb(k2)            , g3*lb(k1)            , 0                    , g0*lb(k1)            , g3*lb(k2)            , 0                    , g4*lb(k1)            , 0                    , g1*lb(k1)            , g4*lb(k2)            , g3*lb(k1)            , 0                    , g2*lb(k1)            , g3*lb(k2)            , 0                    , g5*lb(k1)            , 0                    , 0                    , 0                    , g4*lb(k1)            , g5*lb(k2)            , g6*lb(k1)            , 0                    , g5                   , g4                   , 0                    , g5                   , g3                   , g6                   , g3                   , g1                   , g1                   , g4                   , g0                   , g2                   , e0                   , g1                   , g0                   , g1                   , 0 , 0 , 0 , 0 , 0 , 0 ] , #47
			[ g6*lb(k1)*lb(k2)     , 0                    , 0                    , g6*lb(k2)            , 0                    , g4*lb(k2)            , g6*lb(k2)            , g6*lb(k1)            , g2*lb(k2)            , g5*lb(k2)            , g5*lb(k1)            , g1*lb(k2)            , 0                    , g3*lb(k2)            , g3*lb(k1)            , g0*lb(k2)            , g4*lb(k2)            , 0                    , 0                    , g4*lb(k1)            , g1*lb(k2)            , 0                    , g3*lb(k2)            , g3*lb(k1)            , g2*lb(k2)            , 0                    , 0                    , g5*lb(k2)            , 0                    , 0                    , g5*lb(k1)            , g4*lb(k2)            , 0                    , g6*lb(k2)            , g4                   , g5                   , g5                   , 0                    , g3                   , g3                   , g6                   , g1                   , g4                   , g1                   , g2                   , g0                   , g1                   , e0                   , g0                   , g1                   , 0 , 0 , 0 , 0 , 0 , 0 ] , #48
			[ g4*lb(k1)*lb(k2)     , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , g4*lb(k1)            , g4*lb(k2)            , 0                    , g3*lb(k1)            , g3*lb(k2)            , g5*lb(k1)            , g5*lb(k2)            , g1*lb(k1)            , g1*lb(k2)            , g6*lb(k2)            , g6*lb(k1)            , 0                    , g2*lb(k1)            , g2*lb(k2)            , g4*lb(k1)            , g4*lb(k2)            , g1*lb(k1)            , g1*lb(k2)            , 0                    , g6*lb(k1)            , g6*lb(k2)            , 0                    , 0                    , g3*lb(k1)            , g3*lb(k2)            , g5*lb(k1)            , g5*lb(k2)            , g6                   , g6                   , 0                    , 0                    , g4                   , g5                   , g5                   , g2                   , g3                   , g3                   , g1                   , g1                   , g0                   , g0                   , e0                   , g0                   , 0 , 0 , 0 , 0 , 0 , 0 ] , #49
			[ g2*lb(k1)*lb(k2)     , g4*lb(k1)*lb(k2)     , g6*lb(k1)*lb(k2)     , g6*lb(k1)*lb(k2)     , 0                    , 0                    , 0                    , g6*lb(k1)            , g6*lb(k2)            , 0                    , g4*lb(k1)            , g4*lb(k2)            , g6*lb(k1)            , g6*lb(k2)            , g2*lb(k1)            , g2*lb(k2)            , g5*lb(k2)            , g5*lb(k1)            , 0                    , g1*lb(k1)            , g1*lb(k2)            , g3*lb(k1)            , g3*lb(k2)            , g0*lb(k1)            , g0*lb(k2)            , 0                    , g4*lb(k1)            , g4*lb(k2)            , 0                    , 0                    , g1*lb(k1)            , g1*lb(k2)            , g3*lb(k1)            , g3*lb(k2)            , 0                    , 0                    , g5*lb(k1)            , g5*lb(k2)            , 0                    , 0                    , 0                    , g4                   , g5                   , g5                   , g3                   , g3                   , g1                   , g1                   , g0                   , e0                   , 0 , 0 , 0 , 0 , 0 , 0 ] , #50
                        [ 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #51                       
                        [ 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #52                       
                        [ 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #53                       
                        [ 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #54                       
                        [ 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ] , #55                       
                        [ 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0                    , 0 , 0 , 0 , 0 , 0 , 0 ]]) #56                       
			# 1                    # 2                    # 3                    # 4                    # 5                    # 6                    # 7                    # 8                    # 9                    #10                    #11                    #12                    #13                    #14                    #15                    #16                    #17                    #18                    #19                    #20                    #21                    #22                    #23                    #24                    #25                    #26                    #27                    #28                    #29                    #30                    #31                    #32                    #33                    #34                    #35                    #36                    #37                    #38                    #39                    #40                    #41                    #42                    #43                    #44                    #45                    #46                    #47                    #48                    #49                    #50                    #51 #52 #53 #54 #55 #56                            

	e1=coeff[1] #onsite energy of C 26
	e2=coeff[2] #onsite energy of C 29
	e3=coeff[3] #onsite energy of C 30
	e4=coeff[4] #onsite energy of C 35
	e5=coeff[5] #onsite energy of C 36
	e6=coeff[6] #onsite energy of C 39

	b1=coeff[7] #Cr-C 51-26 d orbitals
	b2=coeff[8]
	b3=coeff[9]
	b4=coeff[10]
	b5=coeff[11]

	b6=coeff[12] #Cr-C 51-{26,29,30,35,36,39} s orbital

	f1=coeff[13] #Cr-C 51-29 d orbitals
	f2=coeff[14]
	f3=coeff[15]
	f4=coeff[16]
	f5=coeff[17]

	h1=coeff[18] #Cr-C 51-30 d orbitals
	h2=coeff[19]
	h3=coeff[20]
	h4=coeff[21]
	h5=coeff[22]

	i1=coeff[23] #Cr-C 51-35 d orbitals
	i2=coeff[24]
	i3=coeff[25]
	i4=coeff[26]
	i5=coeff[27]

	j1=coeff[28] #Cr-C 51-36 d orbitals
	j2=coeff[29]
	j3=coeff[30]
	j4=coeff[31]
	j5=coeff[32]

	k1=coeff[33] #Cr-C 51-39 d orbitals
	k2=coeff[34]
	k3=coeff[35]
	k4=coeff[36]
	k5=coeff[37]

	d1=coeff[38] #onsite energy of Cr d orbitals
	d2=coeff[39]
	d3=coeff[40]
	d4=coeff[41]
	d5=coeff[42]
	d6=coeff[43] #onsite energy of Cr s orbital
	
	a[26-1,26-1]=e1
	a[29-1,29-1]=e2
	a[30-1,30-1]=e3
	a[35-1,35-1]=e4
	a[36-1,36-1]=e5
	a[39-1,39-1]=e6

	a[51-1,26-1]=a[26-1,51-1]=b1
	a[52-1,26-1]=a[26-1,52-1]=b2
	a[53-1,26-1]=a[26-1,53-1]=b3
	a[54-1,26-1]=a[26-1,54-1]=b4
	a[55-1,26-1]=a[26-1,55-1]=b5

	a[56-1,26-1]=a[26-1,56-1]=a[56-1,29-1]=a[29-1,56-1]=a[56-1,30-1]=a[30-1,56-1]=a[56-1,35-1]=a[35-1,56-1]=a[56-1,36-1]=a[36-1,56-1]=a[56-1,39-1]=a[39-1,56-1]=b6

	a[51-1,29-1]=a[29-1,51-1]=f1
	a[52-1,29-1]=a[29-1,52-1]=f2
	a[53-1,29-1]=a[29-1,53-1]=f3
	a[54-1,29-1]=a[29-1,54-1]=f4
	a[55-1,29-1]=a[29-1,55-1]=f5
	
	a[51-1,30-1]=a[30-1,51-1]=h1
	a[52-1,30-1]=a[30-1,52-1]=h2
	a[53-1,30-1]=a[30-1,53-1]=h3
	a[54-1,30-1]=a[30-1,54-1]=h4
	a[55-1,30-1]=a[30-1,55-1]=h5
	
	a[51-1,35-1]=a[35-1,51-1]=i1
	a[52-1,35-1]=a[35-1,52-1]=i2
	a[53-1,35-1]=a[35-1,53-1]=i3
	a[54-1,35-1]=a[35-1,54-1]=i4
	a[55-1,35-1]=a[35-1,55-1]=i5
	
	a[51-1,36-1]=a[36-1,51-1]=j1
	a[52-1,36-1]=a[36-1,52-1]=j2
	a[53-1,36-1]=a[36-1,53-1]=j3
	a[54-1,36-1]=a[36-1,54-1]=j4
	a[55-1,36-1]=a[36-1,55-1]=j5
	
	a[51-1,39-1]=a[39-1,51-1]=k1
	a[52-1,39-1]=a[39-1,52-1]=k2
	a[53-1,39-1]=a[39-1,53-1]=k3
	a[54-1,39-1]=a[39-1,54-1]=k4
	a[55-1,39-1]=a[39-1,55-1]=k5
	
	a[51-1,51-1]=d1
	a[52-1,52-1]=d2
	a[53-1,53-1]=d3
	a[54-1,54-1]=d4
	a[55-1,55-1]=d5
	a[56-1,56-1]=d6

	if not np.allclose(a, np.asmatrix(a).H):
		raise ValueError('expected symmetric or Hermitian matrix,try using numpy.linalg.eig instead')	
	w =  LA.eigvalsh(a)
	r=sorted(w.real)
	i=sorted(w.imag)
	return r




def fitness_function(chromosome):
        global sample_points
        score = 0
	for point in sample_points:
		r = diagonalize(point[0], point[1], *chromosome)
		delta = abs(r[19] - point[2]) + abs(r[20] - point[3]) + abs(r[21] - point[4]) + abs(r[22] - point[5]) + abs(r[23] - point[6]) + abs(r[24] - point[7]) + abs(r[25] - point[8]) + abs(r[26] - point[9]) + abs(r[27] - point[10]) + abs(r[28] - point[11]) + abs(r[29] - point[12]) + abs(r[30] - point[13]) + abs(r[31] - point[14]) + abs(r[32] - point[15]) + abs(r[33] - point[16]) + abs(r[34] - point[17]) + abs(r[35] - point[18]) + abs(r[36] - point[19])
		score += delta
	score = -score
	return score

def main_run():
 global sample_points
 x1 = []
 x2 = []
 x3 = []
 x4 = []
 x5 = []
 x6 = []
 x7 = []
 x8 = []
 x9 = []
 x10 = []
 x11 = []
 x12 = []
 x13 = []
 x14 = []
 x15 = []
 x16 = []
 x17 = []
 x18 = []
 x19 = []
 x20 = []
 x21 = []

 with open('Bands_GMKG-siesta_Cr_hollow.txt','r') as inputfile:
	x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21 = np.loadtxt(inputfile, usecols=(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20), skiprows=1, unpack=True)

 sample_points = []
 for i, aux in enumerate(x1):
	sample_points.append((x1[i],x2[i],x3[i],x4[i],x5[i],x6[i],x7[i],x8[i],x9[i],x10[i],x11[i],x12[i],x13[i],x14[i],x15[i],x16[i],x17[i],x18[i],x19[i],x20[i],x21[i]))

# fitness = fitness_function(coeff)
# print(fitness)

# Enable the pyevolve logging system
 pyevolve.logEnable()

# Create the population
 genome = G1DList.G1DList(44)
#genome.setInternalList(coeff)
 genome.evaluator.set(fitness_function)
 genome.setParams(rangemin=-5, rangemax=5)
 genome.initializator.set(Initializators.G1DListInitializatorReal)
 genome.mutator.set(Mutators.G1DListMutatorRealGaussian)
 genome.crossover.set(Crossovers.G1DListCrossoverUniform)
# Set up the engine
 ga = GSimpleGA.GSimpleGA(genome,123)
 ga.setPopulationSize(3000)
 ga.selector.set(Selectors.GRouletteWheel)
 ga.setGenerations(300)
# ga.setMutationRate(0.05) #Default is 0.02, which represents 0.2%
# ga.setCrossoverRate(0.9)   #Default is 0.9, which represents 90%
# sqlite_adapter = DBAdapters.DBSQLite(identify="gr-Cr-hollow", frequency=100)
# ga.setDBAdapter(sqlite_adapter)
# Change the scaling method
 pop = ga.getPopulation()
 pop.scaleMethod.set(Scaling.SigmaTruncScaling)
 ga.setMultiProcessing(True)
# Start the algorithm, and print the results.
 ga.evolve(freq_stats=10)
# Best individual
 best = ga.bestIndividual()
 print best
# print("Source polynomial: " + repr(source_polynomial))
# print("Sample points: " + repr(sample_points))

# plot graphics

 outtb2=open('output_tb_gr-Cr-hollow.dat','w')
 coeff=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
# coeff=[-2.97, -0.073, -0.33, 0.073, -0.28]
 coeff[0]=best[0]
 coeff[1]=best[1]
 coeff[2]=best[2]
 coeff[3]=best[3]
 coeff[4]=best[4]
 coeff[5]=best[5]
 coeff[6]=best[6]
 coeff[7]=best[7]
 coeff[8]=best[8]
 coeff[9]=best[9]
 coeff[10]=best[10]
 coeff[11]=best[11]
 coeff[12]=best[12]
 coeff[13]=best[13]
 coeff[14]=best[14]
 coeff[15]=best[15]
 coeff[16]=best[16]
 coeff[17]=best[17]
 coeff[18]=best[18]
 coeff[19]=best[19]
 coeff[20]=best[20]
 coeff[21]=best[21]
 coeff[22]=best[22]
 coeff[23]=best[23]
 coeff[24]=best[24]
 coeff[25]=best[25]
 coeff[26]=best[26]
 coeff[27]=best[27]
 coeff[28]=best[28]
 coeff[29]=best[29]
 coeff[30]=best[30]
 coeff[31]=best[31]
 coeff[32]=best[32]
 coeff[33]=best[33]
 coeff[34]=best[34]
 coeff[35]=best[35]
 coeff[36]=best[36]
 coeff[37]=best[37]
 coeff[38]=best[38]
 coeff[39]=best[39]
 coeff[40]=best[40]
 coeff[41]=best[41]
 coeff[42]=best[42]
 coeff[43]=best[43]


 for point in sample_points:
	r = diagonalize(point[0], point[1], *coeff)
	print >> outtb2, point[20], r[19], r[20], r[21], r[22], r[23], r[24], r[25], r[26], r[27], r[28], r[29], r[30], r[31], r[32], r[33], r[34], r[35], r[36], point[2], point[3], point[4], point[5], point[6], point[7], point[8], point[9], point[10], point[11], point[12], point[13], point[14], point[15], point[16], point[17], point[18], point[19]


 outtb2.close()

if __name__ == "__main__":
   main_run()


